services:
  api:
    container_name: paynless-backend
    build: .
    command: poetry run gunicorn -b 0.0.0.0 backend.wsgi:application
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      # for production
      - RENDER=1
