services:
  api:
    container_name: paynless-backend
    build: .
    command: poetry run daphne -b 0.0.0.0 backend.asgi:application
    volumes:
      - ./:/usr/src/app
    ports:
      - 80:8000
    env_file:
      - ./.env
    environment:
      # for production
      - RENDER=1
